project:
  type: website

website:
  title: ""
  favicon: "logos/tae-logo-colour-uniform.png"
  navbar:
    logo: "logos/tae-logo-colour-uniform.png"
    logo-alt: "Logo for The Analytical Edge"
    right:
      - text: "About"
        href: about.qmd
      - text: "Team"
        href: team.qmd
      - text: "What we do"
        href: what-we-do.qmd
      - text: "Case Studies"
        href: case-studies.qmd

  page-footer:
      left: |
        The Analytical Edge Pty Ltd • P O Box 47 Blackmans Bay Tasmania 7052
      right: |
        info@theanalyticaledge.com • Ph: +61 424 664 954
      background: "#00aeefff"
      foreground: "#FFFFFF"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

