project:
  type: website

website:
  title: ""
  back-to-top-navigation: true
  favicon: "logos/tae_fav.png"
  navbar:
    logo: "logos/tae_logo.png"
    logo-alt: "Logo for The Analytical Edge"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: index.qmd#about-us
      - text: "Team"
        href: team.qmd
      - text: "Case Studies"
        href: case-studies.qmd

  page-footer:
      left: |
        The Analytical Edge Pty Ltd • P O Box 47 Blackmans Bay Tasmania 7052
      right: |
        info@theanalyticaledge.com • Ph: +61 424 664 954
      background: "#00aeefff"
      foreground: "#FFFFFF"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

