---
title: ""
---

We are a network of statisticians, ecologists, and biosecurity experts, whose work supports diverse stakeholders such as academia, government and the private sector, to achieve their goals.

Developing stage-structured population models for an endangered plant species

Our services include:

-   Use of risk-based investigative tools for assessing the consequences of management actions

-   Designing surveillance protocols to eradicate diseases within agricultural settings

-   Survey design to estimate animal and plant abundance

-   Analysis of data collected via active underwater acoustics to analyse migration patterns

-   Survey design and data analysis for population modelling, including species spread and population growth in landscapes

-   Application of sophisticated data analysis techniques to publish research in high impact, peer-reviewed journals

-   Delivery of technical workshops on statistical topics

Please refer to [How we can help you](https://www.theanalyticaledge.com/how-we-can-help.html) for further information.
