---
title: "SPSS workshop"
subtitle: "Presenter: Russell"
image: "../people/Jo headshot (h)-1.jpg"
format:
  html:
    page-layout: full
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.theanalyticaledge\.com\/custom'
about:
    id: about-block
    template: trestles
    image-shape: round
    links:
      - icon: envelope
        text: "Email"
        href: "mailto:joanne@theanalyticaledge.com"
---

This course is run by russell.

**Professional background**

After completing her undergraduate degree in Applied Statistics and Environmental Science at the University of Melbourne, Joanne worked as a consultant statistician at the [Arthur Rylah Institute for Ecological Research](https://www.ari.vic.gov.au) within the Government of Victoria, where she conducted ecological research in a areas such as the [impact of salinization](http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2427.2006.01672.x/abstract), and [habitat fragmentation](http://www.publish.csiro.au/nid/144/display/citation/paper/WR07010.htm).

In 2006, Joanne moved to the [Centre for Research into Ecological and Environmental Modelling](http://creem2.st-andrews.ac.uk/) at University of St Andrews in Scotland, to undertake her PhD studies. She was supervised by Prof. Stephen Buckland, Dr. Len Thomas, and Dr Anne Savage, and developed methods for incorporating animal movement data into capture-recapture analysis for [abundance estimation for small mammals](http://onlinelibrary.wiley.com/doi/10.1111/j.2041-210X.2012.00205.x/abstract) and [compared abundance estimation techniques](https://wildlife.onlinelibrary.wiley.com/doi/abs/10.1002/wsb.651).

See Joanne's [Google Scholar Profile](https://scholar.google.com.au/citations?user=XnnIFvAAAAAJ&hl=en) for an up-to-date record of her peer-reviewed scientific publications.
